name: Hello CI
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['.github/workflows/hello-ci.yml']
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello from repo1
